# Generated by Django 3.1.2 on 2020-11-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.SlugField(max_length=30)),
                ('image', models.CharField(max_length=40)),
                ('name1', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=80)),
                ('address', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
